apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastify-user-dpl2
  labels:
    app: fastify-user-dpl2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastify-user
  template:
    metadata:
      labels:
        app: fastify-user
    spec:
      containers:
      - name: fastify-user-cont
        image: jksnu/mynodeapi
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: "development"
        - name: ALLOWED_ORIGINS
          value: "http://localhost:4200,http://localhost:9000,http://localhost:4200/api"
        - name: OAUTH_JWKS_API
          value: "http://localhost:7000/jwks/"
